apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: "0.8.3"
    namespace: external-secrets