{{- if .Values.certManager.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.12.2
    helm:
      values: |
        {{ .Values.certManager.values | toYaml | indent 8 | trim}}
    chart: cert-manager
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{- end }}