{{- if .Values.metricsServer.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations: 
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.9.0
    helm:
      values: |
        {{ .Values.metricsServer.values | toYaml | indent 8 | trim}}
  syncPolicy:
    automated:
      prune: true
{{- end }}