{{- if .Values.rancher.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://releases.rancher.com/server-charts/stable'
    targetRevision: v2.7.4
    helm:
      parameters:
        - name: hostname
          value: {{ .Values.rancher.hostname }}
        - name: tls
          value: {{ .Values.rancher.tls }}
        - name: boostrapPassword
          value: {{ .Values.rancher.bootstrapPassword }}
        - name: ingress.ingressClassName
          value: {{ .Values.rancher.ingressClassName }}
    chart: rancher
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cattle-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{- end }}