# ArgoCD App of Apps pattern that manages the cluster
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  labels:
    name: app-of-apps
spec:
  source:
    # TODO: secret for repo connection
    repoURL: "https://github.com/kloia/ArgoCD-EKS-Bootstrapper.git"
    targetRevision: kustomize
    # make sure to patch this according to the cluster overlay
    path: clusters/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  syncPolicy:
    automated:
      selfHeal: true

