# Cert Manager
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    name: cert-manager
spec:
  source:
    repoURL: "https://github.com/kloia/ArgoCD-EKS-Bootstrapper.git"
    targetRevision: kustomize
    path: apps/cert-manager/base
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
