apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/applications/app-of-apps.yaml
  - resources/applications/argocd.yaml
  - resources/applications/cert-manager.yaml
  - resources/applications/external-secrets-operator.yaml