# External Secrets Operator
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  labels:
    name: external-secrets-operator
spec:
  source:
    repoURL: "https://github.com/kloia/ArgoCD-EKS-Bootstrapper.git"
    targetRevision: kustomize
    path: examples/argocd-with-kustomize/apps/external-secrets-operator/base
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      selfHeal: true
