apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: kuard-staging

nameSuffix: -staging

images:
  - name: gcr.io/kuar-demo/kuard-amd64:blue
    newTag: purple

