# Default values for bootstrap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ssl:
  enabled: false
  domain: "kloia.com" 
kyverno:
  enable: false  
logging:
  enable: false
monitoring:
  enable: false
  pdkey:
  storageSize: 50Gi
  retention: 5d  
trivy:
  enable: true
metricsServer:
  enable: true
  values: 
    hostNetwork:
      enabled: true
certManager:
  enable: true
  values:
    installCRDs: "true"
    prometheus:
      servicemonitor:
        enabled: "false"
        honorLabels: "false"
rancher:
  enable: false
  values:
    hostname: "rancher.kloia.com"
    tls: "external"
    bootstrapPassword: "admin"
    ingress:
      ingressClassName: "nginx"
rancherMonitoringCrd:
  enable: false
  chartsRepoTargetRevision: "dev-v2.7"
  version: "102.0.1+up40.1.2"
rancherMonitoring:
  enable: false
  chartsRepoTargetRevision: "release-v2.7"
  version: "102.0.0+up40.1.2"
rancherIstio:
  enable: false
  chartsRepoTargetRevision: "dev-v2.7"
  version: "102.0.1+up40.1.2"
  values:
    tracing:
      enabled: true

connectAlbToIstio:
  enable: false
  targetRevision: "0.2.0"
  values:
    name: connect-alb-to-istio
    alb:
      # when using, make sure to add certificate
      scheme: internet-facing
      target-type: instance
      backend-protocol: HTTPS
      healthcheck-path: "/healthz/ready"
      healthcheck-protocol: HTTP
      listen-ports:
        - HTTP: 80
        - HTTPS: 443
      actions.ssl-redirect:
        Type: redirect
        RedirectConfig:
          Protocol: HTTPS
          Port: "443"
          StatusCode: HTTP_301
    spec:
      ingressClassName: alb
      rules:
        - http:
            paths:
              - backend:
                  service:
                    name: ssl-redirect
                    port:
                      name: use-annotation
                  path: /
                pathType: Prefix
              - backend:
                  service:
                    name: istio-ingressgateway
                    port:
                      number: 15021
                  path: /healthz/ready
                pathType: Prefix
              - backend:
                  service:
                    name: istio-ingressgateway
                    port:
                      number: 443
                  path: /
                pathType: Prefix
