# Default values for bootstrap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ssl:
  enabled: false
  domain: "kloia.com" 
kyverno:
  enable: false  
logging:
  enable: false
monitoring:
  enable: false
  pdkey:
  storageSize: 50Gi
  retention: 5d  
trivy:
  enable: true
metricsServer:
  enable: true
  values: 
    hostNetwork:
      enabled: true
certManager:
  enable: true
  values:
    installCRDs: "true"
    prometheus:
      servicemonitor:
        enabled: "false"
        honorLabels: "false"
rancher:
  enable: false
  targetRevision: v2.7.9
  values:
    hostname: "rancher.kloia.com"
    tls: "external"
    bootstrapPassword: "admin"
    ingress:
      ingressClassName: "nginx"
rancherBackupCrd:
  enable: false
  version: "102.0.0+up3.1.0"
rancherBackup:
  enable: false
  version: "102.0.0+up3.1.0"
rancherMonitoringCrd:
  enable: false
  version: "102.0.0+up40.1.2"
rancherMonitoring:
  enable: false
  version: "102.0.0+up40.1.2"
rancherIstio:
  enable: false
  version: "102.2.0+up1.17.2"
  values:
    tracing:
      enabled: true
neuvector:
  enable: false
  version: "102.0.0+up2.4.2"
  targetRevision: v2.7
  values:
    containerd:
      enabled: true
      path: /run/containerd/containerd.sock
    global:
      cattle:
        url: "https://rancher.kloia.com"
rancherLogging:
  enable: false
  version: "102.0.0+up3.17.10"
  targetRevision: v2.7
argoWorkflow:
  enable: false
  targetRevision: "0.33.2"
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - workflows.kloia.com
      extraArgs:
      - --auth-mode=server
hivemq:
  enable: false
  values:
atlantis:
  enable: true
  targetRevision: "4.19.0"
  values:
